### PR TITLE
Swift 4.0

### PR DESCRIPTION
**Pull request by kaosdg**
So this PR uses the `withoutActuallyEscaping(_:do:)` wrapper function to handle closure arguments in the generated mocks.

Not terribly happy about the implementation - basically I created an "open / close" template filter to be able to write those nested closures, and tried to cover the case where there may be multiple non-escaping closure args.

I think it's ugly, but it works...  if anyone has a better way I'm open to suggestion and collaboration...
  (perhaps Stencil can do this natively?  I'm not too familiar with it)

### CODE REVIEW

**Comment by bsarrazin** [comment]
@kaosdg thanks for doing all this work. Truly appreciated. However, I'm still getting some errors in the generated mocks:

```
Invalid conversion from throwing function of type '((CredentialsManager) throws -> _) throws -> _?' to non-throwing function type '((CredentialsManager) throws -> () -> CredentialsInfo?) -> ((_) -> _)?'
```

**Comment by kaosdg** [comment]
@bsarrazin can you give me an example of your function?

**Comment by kaosdg** [comment]
@bsarrazin I just pushed up a few changes to handle some throwing methods with throwing closures, can you give that a test run in your case?

**Comment by bsarrazin** [comment]
@kaosdg after taking a bit of a deeper dive, the problems seems to be in the generated code. Our code doesn't have throwing functions (like in the example above), they are simple functions. The generated code has them and caused the following errors:

```
../SharedMocks/PlatformKit.swift:47:32: Invalid conversion from throwing function of type '((CredentialsManager) throws -> _) throws -> _?' to non-throwing function type '((CredentialsManager) throws -> () -> CredentialsInfo?) -> ((_) -> _)?'
../SharedMocks/PlatformKit.swift:71:32: Invalid conversion from throwing function of type '((CredentialsManager) throws -> _) throws -> _?' to non-throwing function type '((CredentialsManager) throws -> () -> ()) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:699:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, String, Date?, Bool, Bool), original: ((String, String, Date?, Bool, Bool) -> Observable<PKAssetResponse>)?)'
../SharedMocks/DomainKit.swift:699:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3, IN4, IN5), original: (((IN1, IN2, IN3, IN4, IN5)) -> OUT)?)
../SharedMocks/DomainKit.swift:873:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, String, String, String?, PhoneColor?), original: ((String, String, String, String?, PhoneColor?) -> Observable<PKAssetResponse>)?)'
../SharedMocks/DomainKit.swift:873:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3, IN4, IN5), original: (((IN1, IN2, IN3, IN4, IN5)) -> OUT)?)
../SharedMocks/DomainKit.swift:1157:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (Data, String, String), original: ((Data, String, String) -> Observable<PKFileInfo>)?)'
../SharedMocks/DomainKit.swift:1157:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3), original: (((IN1, IN2, IN3)) -> OUT)?)
../SharedMocks/DomainKit.swift:1169:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, String, String), original: ((String, String, String) -> Observable<PromotionalPriceOfferAccepted>)?)'
../SharedMocks/DomainKit.swift:1169:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3), original: (((IN1, IN2, IN3)) -> OUT)?)
../SharedMocks/DomainKit.swift:1515:32: Invalid conversion from throwing function of type '((AssetLocalGateway) throws -> _) throws -> _?' to non-throwing function type '((AssetLocalGateway) throws -> () -> ()) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:1585:31: Cannot invoke 'call' with an argument list of type '(String, parameters: ([REDACTED].ID, AssetCategory), original: (([REDACTED].ID, AssetCategory) -> Observable<Asset>)?)'
../SharedMocks/DomainKit.swift:1585:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:1599:32: Invalid conversion from throwing function of type '((AssetLocalGateway) throws -> _) throws -> _?' to non-throwing function type '((AssetLocalGateway) throws -> () -> Observable<Asset>) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:2228:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, Bool?), original: ((String, Bool?) -> PrimitiveSequence<SingleTrait, PKPaymentCard>)?)'
../SharedMocks/DomainKit.swift:2228:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:2325:32: Invalid conversion from throwing function of type '((ChatBotGateway) throws -> _) throws -> _?' to non-throwing function type '((ChatBotGateway) throws -> () -> Observable<Void>) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:2335:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (Participant, String), original: ((Participant, String) -> Observable<Void>)?)'
../SharedMocks/DomainKit.swift:2335:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:2349:32: Invalid conversion from throwing function of type '((ChatBotGateway) throws -> _) throws -> _?' to non-throwing function type '((ChatBotGateway) throws -> () -> Observable<Activity>) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:2479:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, String, String, Int), original: ((String, String, String, Int) -> ())?)'
../SharedMocks/DomainKit.swift:2479:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3, IN4), original: (((IN1, IN2, IN3, IN4)) -> OUT)?)
../SharedMocks/DomainKit.swift:2491:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (Error, [String : AnyObject]?), original: ((Error, [String : AnyObject]?) -> ())?)'
../SharedMocks/DomainKit.swift:2491:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:2600:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, String), original: ((String, String) -> Observable<LoginInfo>)?)'
../SharedMocks/DomainKit.swift:2600:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:3412:32: Invalid conversion from throwing function of type '((AutoSuggestLocalGateway) throws -> _) throws -> _?' to non-throwing function type '((AutoSuggestLocalGateway) throws -> () -> Observable<Void>) -> ((_) -> _)?'
../SharedMocks/DomainKit.swift:3534:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, [AnyHashable : Any]), original: ((String, [AnyHashable : Any]) -> ())?)'
../SharedMocks/DomainKit.swift:3534:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:3546:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (String, [AnyHashable : Any]), original: ((String, [AnyHashable : Any]) -> ())?)'
../SharedMocks/DomainKit.swift:3546:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/DomainKit.swift:3705:32: Invalid conversion from throwing function of type '(([REDACTED]RemoteGateway) throws -> _) throws -> _?' to non-throwing function type '(([REDACTED]RemoteGateway) throws -> () -> Observable<[REDACTED]>) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:3173:71: Invalid conversion from throwing function of type '((CoreDataController) throws -> _) throws -> _?' to non-throwing function type '((CoreDataController) throws -> () -> PersistenceConfiguration) -> ((()) -> _)?'
../SharedMocks/AdapterKit.swift:3611:74: Invalid conversion from throwing function of type '((DirectLineChatBotGateway) throws -> _) throws -> _?' to non-throwing function type '((DirectLineChatBotGateway) throws -> () -> SchedulerType) -> ((()) -> _)?'
../SharedMocks/AdapterKit.swift:28:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (Participant, String), original: ((Participant, String) -> JSONDictionary)?)'
../SharedMocks/AdapterKit.swift:28:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:588:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (MigrationManager, Float), original: ((MigrationManager, Float) -> ())?)'
../SharedMocks/AdapterKit.swift:588:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:698:35: Cannot invoke 'callThrows' with an argument list of type '(String, parameters: (URL, String, NSManagedObjectModel), original: ((URL, String, NSManagedObjectModel) throws -> Bool)?)'
../SharedMocks/AdapterKit.swift:698:35: Overloads for 'callThrows' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) throws -> OUT)?), (String, parameters: (IN1, IN2, IN3), original: (((IN1, IN2, IN3)) throws -> OUT)?)
../SharedMocks/AdapterKit.swift:734:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (NSManagedObjectModel, String, URL, [String : AnyObject]?), original: ((NSManagedObjectModel, String, URL, [String : AnyObject]?) -> MigrationManager.CoordinatorStore)?)'
../SharedMocks/AdapterKit.swift:734:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2, IN3, IN4), original: (((IN1, IN2, IN3, IN4)) -> OUT)?)
../SharedMocks/AdapterKit.swift:1024:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (DirectLineEnvironment, String), original: ((DirectLineEnvironment, String) -> Observable<JSONDictionary>)?)'
../SharedMocks/AdapterKit.swift:1024:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:1036:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (DirectLineEnvironment, String), original: ((DirectLineEnvironment, String) -> Observable<JSONDictionary>)?)'
../SharedMocks/AdapterKit.swift:1036:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:1072:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (ConversationParameters, JSONDictionary), original: ((ConversationParameters, JSONDictionary) -> Observable<JSONDictionary>)?)'
../SharedMocks/AdapterKit.swift:1072:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:2120:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () -> ManagedObjectContext!) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:2132:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () -> ()) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:2144:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () -> ManagedObjectContext) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:2168:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () -> NSPersistentStoreCoordinator!) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:2180:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () -> ()) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:2192:32: Invalid conversion from throwing function of type '((CoreDataService) throws -> _) throws -> _?' to non-throwing function type '((CoreDataService) throws -> () throws -> ()) -> ((_) throws -> _)?'
../SharedMocks/AdapterKit.swift:3298:32: Invalid conversion from throwing function of type '((CoreDataController) throws -> _) throws -> _?' to non-throwing function type '((CoreDataController) throws -> () throws -> ()) -> ((_) throws -> _)?'
../SharedMocks/AdapterKit.swift:3310:32: Invalid conversion from throwing function of type '((CoreDataController) throws -> _) throws -> _?' to non-throwing function type '((CoreDataController) throws -> () -> ()) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:3628:32: Invalid conversion from throwing function of type '((DirectLineChatBotGateway) throws -> _) throws -> _?' to non-throwing function type '((DirectLineChatBotGateway) throws -> () -> Observable<Void>) -> ((_) -> _)?'
../SharedMocks/AdapterKit.swift:3638:31: Cannot invoke 'call' with an argument list of type '(String, parameters: (Participant, String), original: ((Participant, String) -> Observable<Void>)?)'
../SharedMocks/AdapterKit.swift:3638:31: Overloads for 'call' exist with these partially matching parameter lists: (String, parameters: IN, original: ((IN) -> OUT)?), (String, parameters: (IN1, IN2), original: (((IN1, IN2)) -> OUT)?)
../SharedMocks/AdapterKit.swift:3652:32: Invalid conversion from throwing function of type '((DirectLineChatBotGateway) throws -> _) throws -> _?' to non-throwing function type '((DirectLineChatBotGateway) throws -> () -> Observable<Activity>) -> ((_) -> _)?'
```

**Comment by kaosdg** [comment]
@bsarrazin those errors look a lot like the errors i was getting before i implemented `withoutActuallyEscaping(_:do:)`

Have you tried updating to my latest commit? (you might need to clear pod caches if you are using cocoapods)

**Comment by bsarrazin** [comment]
is there an ETA on merging this and releasing a new version of Cuckoo?

**Comment by TadeasKriz** [comment]
@bsarrazin Hey, I'll be back in office on 30th September and I'd like to do some quick testing of this PR and then merge it. I'm sorry for the delay.

**Comment by TadeasKriz** [comment]
Thank you @kaosdg for this PR!

**Comment by bsarrazin** [comment]
@TadeasKriz @kaosdg thank you for your efforts on this!
Tremendously appreciated!

**Pull request merged**
