### PR TITLE
Add property attributes to stubs and proxies

### PR DESCRIPTION
**Pull request by dmazzoni**
Adds property attributes to the templates of stubbing proxies, verification proxies and stubs.

For example, this is required for the following example protocol to be mockable with a deployment target lower than the iOS version specified in the `@available` attribute (suppose that `Baz` was introduced with iOS 12):

```
protocol Bar {
    
    @available(iOS 12.0, *)
    var foo: Baz? { get }
}
```

If the `@available` attribute is not included in stubs and proxies, Cuckoo's output file will not compile.

### CODE REVIEW

**Comment by MatyasKriz** [comment]
Huh, nice catch. I don't know why I didn't think to include that in the tests. Do you think you could also create an annotated variable inside the `TestedClass` in `TestedClass.swift` as a sort of fail-safe that tests this scenario?

**Comment by TadeasKriz** [comment]
This looks very good! Could you please add tests @MatyasKriz mentioned? Thanks you for the contribution!

**Comment by dmazzoni** [comment]
No problem, I'll update the PR tomorrow!

**Comment by TadeasKriz** [comment]
iOS 42 :D

**Comment by MatyasKriz** [comment]
Merged, thanks!

**Pull request closed without merging**
