### PR TITLE
Generate public variables and functions in public classes.

### LINKED ISSUE #258: Dealing with internal fields
I have an error inside generated file: *Overriding var must be as accessible as its enclosing type Insert 'public'*
But field is not public, it has an internal type:

In original file:
   ```
   internal var disposable: Disposable? = nil
   ```

In generated file:
   ```
  override var disposable: Disposable? {
        get {
            return cuckoo_manager.getter("disposable",
                superclassCall:
                    
                    super.disposable
                    ,
                defaultCall: __defaultImplStub!.disposable)
        }
        
        set {
            cuckoo_manager.setter("disposable",
                value: newValue,
                superclassCall:
                    
                    super.disposable = newValue
                    ,
                defaultCall: __defaultImplStub!.disposable = newValue)
        }
        
    }
```

What I am doing wrong? Thank you for your answers!

### PR DESCRIPTION
**Pull request by MatyasKriz**
Closes #258.

### CODE REVIEW

**Comment by adotor** [comment]
Is there a reason why this ( and several other bugfixes related to the visibility of properties) are postponed and neither merged into the master nor released?

**Comment by TadeasKriz** [comment]
This repository's core maintainer, @MatyasKriz is currently on leave. Once he returns, all the approved PRs will be merged. Thank you for your patience.

**Comment by adotor** [comment]
Any idea when this will be?

**Comment by MatyasKriz** [comment]
Yes, once I successfully turn in my bachelor's thesis. If you're this impatient and are blocked by the unmerged PRs (it takes some time to resolve conflicts and what not, just so you know), pick one of the branches that suits your needs best and use that one until it's done.

You can rest assured that once I do have the time, all the PRs will get merged and released. No need to push it.

**Comment by MatyasKriz** [comment]
@adotor, the PR has been merged, give it a try!

**Pull request closed without merging**
