### PR TITLE
Add Swift Package Manager support.

### LINKED ISSUE #26: Add support for Linux

### LINKED ISSUE #174: Support for Swift Package Manager
Any plans on supporting Swift Package Manager installs?

### PR DESCRIPTION
**Pull request by MatyasKriz**
First time after a long time fiddling with SwiftPM, so I might be forgetting something here.
This PR is set out to resolve #26 and resolve #174.

### CODE REVIEW

**Comment by TadeasKriz** [comment]
The problem here is running the generator. With Swift PM we don't get the `run` downloaded or the generator binary. So we need to add info on how to do it to Readme. The Package.swift looks good.

**Comment by Petter-W** [comment]
Any update on this? What's missing? :)

**Comment by MatyasKriz** [comment]
Hey, @Petter-W. We don't really use SwiftPM, so it's not tested as of now. I've already broken Carthage support for 1.2.0+, so I'd rather resolve that one first before pushing out something that's untested and is potentially broken.

**Comment by davisford** [comment]
LGTM

**Comment by mRs-** [comment]
What's missing here. Would like to ditch Carthage and would like to jump on the package manager train. Maybe I can get the newest version directly here?

**Comment by MatyasKriz** [comment]
I'll try to take a look by the end of the week to see what's missing, test it and hopefully release it if there are no problems.

**Comment by MatyasKriz** [comment]
Hey guys, 1.3.1 is officially the first version to support Swift Package Manager!

Enjoy and of course file an issue if you encounter any problems.

**Pull request closed without merging**
